### ISSUE TITLE
提交到Chrome应用商店

### ISSUE THREAD

**Issue by tuhaihe** [CSDN-Geek/Chrome-Extension#1]
目前要提交扩展到Chrome应用商店，需要开启Google的开发者身份，交付5美元进行验证。
在开通过程中，发现并不支持大陆银行信用卡。

如果你已取得开发者身份，欢迎联络，帮忙上传到Chrome应用商店，发红包哈哈哈~

**Comment by JiYangE** [comment]
是否还需要帮忙
